### PR TITLE
[tests-Only][full-ci] Cancel Old running builds

### PR DESCRIPTION
**Pull request by jasson99**
https://github.com/owncloud/QA/issues/674
- Cancel Old running builds of a PR
**note** this PR was generated by a automated script

Added 2021-09-05: Update .drone.star and drop PHP 7.2
Part of issue https://github.com/owncloud/core/issues/39134
and https://github.com/owncloud/QA/issues/687

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiCoreMKey-50-50-master-mysql8.0-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/encryption/2038/82/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiCoreMKey-50-45-master-mysql8.0-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/encryption/2038/77/1

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
Note: need to look into existing failures in CI.

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiCoreMKey-50-13-master-mysql8.0-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/encryption/2067/40/1

**Comment by phil-davis** [comment]
drone CI passed - :rocket: 

There is a known problem with SonarCloud today. I will override and merge.

**Pull request merged**
