### PR TITLE
[CI] Updated drone.star file to match latest changes

### PR DESCRIPTION
**Pull request by grgprarup**
## Description
This is an update on drone.star file 
- using drone-cancel-previous-builds
- using thegeeklab/drone-github-comment instead of jmccann/drone-github-comment for github comments 
- moving docker image references to constants
- using caches images
- Do not run PHP unit tests with Oracle by default
- Skip pipelines based on changed code

## Related Issue
Part of: 
- https://github.com/owncloud/QA/issues/700
- https://github.com/owncloud/QA/issues/717
- https://github.com/owncloud/QA/issues/729
- https://github.com/owncloud/QA/issues/728
- https://github.com/owncloud/core/issues/38679
- https://github.com/owncloud/QA/issues/730

### CODE REVIEW

**Review by kiranparajuli589 — COMMENTED** [review]
lgtm :+1:  one thing I noticed here is there are some hard-coded directory references. you can also change them in this enhancement pr i think.

**Review by SagarGi — COMMENTED** [review]
lgtm

**Comment by grgprarup** [comment]
> 

@kiranparajuli589 IMO firstly this optimization must be done in activity app then we can replicate to other apps. So its better to create new issue for that.

**Comment by grgprarup** [comment]
> lgtm +1 one thing I noticed here is there are some hard-coded directory references. you can also change them in this enhancement pr i think.

@kiranparajuli589 IMO firstly this optimization must be done in activity app then we can replicate to other apps. So its better to create new issue for that.

**Comment by kiranparajuli589** [comment]
> > lgtm +1 one thing I noticed here is there are some hard-coded directory references. you can also change them in this enhancement pr i think.
> 
> @kiranparajuli589 IMO firstly this optimization must be done in activity app then we can replicate to other apps. So its better to create new issue for that.

issued here https://github.com/owncloud/QA/issues/734

**Comment by kiranparajuli589** [comment]
lgtm from my side :+1:

**Review by kiranparajuli589 — COMMENTED** [review]
lgtm :+1:

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
