### PR TITLE
Use unique usernames in unit tests

### PR DESCRIPTION
**Pull request by sharidas**
Use unique usernames in unit tests.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

### CODE REVIEW

**Comment by sharidas** [comment]
- Fixes https://github.com/owncloud/encryption/issues/79

**Comment by sharidas** [comment]
- Grepped through the `tests` directory for `createUser` and replaced the hard coded user name with output from `$this->getUniqueID()` in the unit test.

**Comment by PVince81** [comment]
seems $userName isn't used properly everywhere:
```
1) OCA\Encryption\Tests\Crypto\EncryptAllTest::testEncryptFileFileId
touch(): Unable to create file /var/www/owncloud/data/user1/files/bar.txt because No such file or directory

/var/www/owncloud/lib/private/Files/Storage/Local.php:218
/var/www/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php:350
/var/www/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php:350
/var/www/owncloud/lib/private/Files/View.php:1186
/var/www/owncloud/lib/private/Files/View.php:563
/var/www/owncloud/apps/encryption/tests/unit/Crypto/EncryptAllTest.php:397

ERRORS!
```

**Comment by sharidas** [comment]
@PVince81 Ouch, yes there were places in the unit test where `$userName` should have been used. I have updated the PR and tested locally:
```
➜  encryption git:(fixunittest-uniqueusers) ✗ make test-php-unit
php -d zend.enable_gc=0 ../../lib/composer/bin/phpunit --configuration ./phpunit.xml --testsuite unit
Cannot load Xdebug - it was already loaded
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.2.12-1+ubuntu18.04.1+deb.sury.org+1 with Xdebug 2.6.1
Configuration: /home/sujith/test/owncloud3/apps/encryption/phpunit.xml

...............................................................  63 / 222 ( 28%)
............................................................... 126 / 222 ( 56%)
............................................................... 189 / 222 ( 85%)
.................................                               222 / 222 (100%)

Time: 21.75 seconds, Memory: 40.00MB

OK (222 tests, 680 assertions)

Generating code coverage report in Clover XML format ... done
➜  encryption git:(fixunittest-uniqueusers) ✗
```

**Pull request merged**
