### PR TITLE
[Tests-Only][CI] Update .drone.star file for new changes from activity app

### PR DESCRIPTION
**Pull request by dpakach**
Related https://github.com/owncloud/QA/issues/678
- Fix code coverage reporting
- Implement early fail and full-ci in drone CI behavior like what is done in core and other repos

**note** this PR was generated by a automated script

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
`starlark: maximum file size exceeded`
https://drone.owncloud.com/owncloud/encryption/1976

stupid thing!

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/encryption/1985/68/18
```
time="2021-07-05T09:40:20Z" level=fatal msg="POST https://api.github.com/repos/owncloud/encryption/issues/294/comments: 422 Validation Failed [{Resource:IssueComment Field:data Code:unprocessable Message:Body cannot be blank}]" 
```

https://drone.owncloud.com/owncloud/encryption/1985/68/17
```
...
>> /drone/src/comments.file
```

The acceptance test step failed. The build-github-comment step is putting the comment text into a file in `drone/src`. But I suspect that the github-comment step has a default directory in a different place.

I will push a fix for that - probably it will need to be fixed in all oC10 apps!

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiCoreMKey-50-38-master-mysql8.0-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/encryption/1986/68/1

**Comment by phil-davis** [comment]
> boom Acceptance tests pipeline **apiCoreMKey-50-38-master-mysql8.0-php7.2** failed. The build has been cancelled.
> 
> https://drone.owncloud.com/owncloud/encryption/1986/68/1

Good - at least I now know that it correctly reports acceptance test failure.

**Comment by phil-davis** [comment]
core PR https://github.com/owncloud/core/pull/38922 was merged today. We are running the very latest test code from core master, that has changed tests for public link upload. But `daily-master-qa` only has core code from last night. So we get:
https://drone.owncloud.com/owncloud/encryption/1986/68/16
```
runsh: Total unexpected failed scenarios throughout the test run:
apiWebdavLocks/publicLink.feature:32
apiWebdavLocks/publicLink.feature:33
apiWebdavLocks/publicLink.feature:34
apiWebdavLocks/publicLink.feature:35
apiWebdavLocks/publicLink.feature:49
apiWebdavLocks/publicLink.feature:50
apiWebdavLocks/publicLink.feature:67
apiWebdavLocks/publicLink.feature:68
apiWebdavLocks/publicLink.feature:87
apiWebdavLocks/publicLink.feature:88
apiWebdavLocks/requestsWithToken.feature:106
apiWebdavLocks/requestsWithToken.feature:107
runsh: There were no unexpected success.
```

This should pass tomorrow, when `daily-master-qa` has been updated overnight.

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiUserKeys-latest-postgres9.4-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/encryption/1988/28/1

**Pull request merged**
