### PR TITLE
Inttest running on encryption

### PR DESCRIPTION
**Pull request by SergioBertolinSG**
Trying to run the tests which used to run in jenkins nightly in this repo.

### CODE REVIEW

**Comment by SergioBertolinSG** [comment]
Travis says: "The job exceeded the maximum time limit for jobs, and has been terminated."

There is a way to increase the time limit?

**Comment by phil-davis** [comment]
I don't think so - Travis puts a 50 minute limit on each job. We had this trouble with UI tests and split them into suites in separate jobs. But I am surprised that these tests would run that long. I see that the Travis log does not have any places that it stops for a long time, so it seems that it really did execute that long.

This ran on Jenkins in core, didn't it?
I guess the Jenkins machine was faster than the VMs that Travis provides.

**Comment by SergioBertolinSG** [comment]
Taking some data from jenkins, the last correct execution of the suite using encryption took ~ 90 minutes. (Without encryption ~43m).

So I see we have several options: 
  - Run these tests in private travis.com, according to travis docs the limit there is 120m https://docs.travis-ci.com/user/customizing-the-build/#Build-Timeouts .
 - Run these tests in private drone.
 - Run there tests in public jenkins again somehow.
 - Improve the core test suite to be able to split the contexts and run them in separated jobs (not immediate solution and needs to allocate time for doing it).

**Comment by DeepDiver1975** [comment]
> Run these tests in private travis.com, according to travis docs the limit there is 120m https://docs.travis-ci.com/user/customizing-the-build/#Build-Timeouts .

not an option - travis-ci.com is for private repos

**Comment by DeepDiver1975** [comment]
> Run these tests in private drone.

lets walk this path - but we need to wait for @tboerger

**Comment by PVince81** [comment]
moving to "planned" for the next iteration

**Comment by patrickjahns** [comment]
Testing with drone to be done here #30

**Comment by PVince81** [comment]
as I understand this is obsoleted by https://github.com/owncloud/encryption/pull/30

**Pull request closed without merging**
