### PR TITLE
Fix re-encrypting encrypted files

### PR DESCRIPTION
**Pull request by sharidas**
When the files are already encrypted the
files need not be encrypted again.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

### CODE REVIEW

**Comment by sharidas** [comment]
fixes https://github.com/owncloud/encryption/issues/52

**Comment by sharidas** [comment]
Below are the tests done to verify it. 
#### Master key encryption
- Create 2 users `admin` and `user1` and encrypt with masterkey.
- Decrypt `user1` files.
- Execute encrypt-all. Below are the console log to verify the result:
```
➜  owncloud3 git:(master) ✗ rm -fr config/config.php data; ./occ maintenance:install --admin-user "admin" --admin-pass "admin"; ./occ a:e user_management; ./occ a:e encryption; ./occ encryption:enable; ./occ encryption:select-encryption-type masterkey -y; ./occ user:add user1
Cannot load Xdebug - it was already loaded
creating sqlite db
ownCloud was successfully installed
Cannot load Xdebug - it was already loaded
user_management enabled
Cannot load Xdebug - it was already loaded
encryption enabled
Cannot load Xdebug - it was already loaded
Encryption enabled

Default module: OC_DEFAULT_MODULE
Cannot load Xdebug - it was already loaded
Master key successfully enabled.
Cannot load Xdebug - it was already loaded
Enter password: 
Confirm password: 
The user "user1" was created successfully
➜  owncloud3 git:(master) ✗ ./occ encryption:decrypt-all user1
Cannot load Xdebug - it was already loaded
Disable server side encryption... done.


You are about to start to decrypt all files stored in user1's account.
It will depend on the encryption module and your setup if this is possible.
Depending on the number and size of your files this can take some time
Please make sure that no user access his files during this process!

Do you really want to continue? (y/n) y
prepare encryption modules...

Prepare "Default encryption module"

Using master key for decryption
 done.


 decrypt files for user user1 (1 of 1): /user1/files/welcome.txt 
 [-->-------------------------]

 starting to decrypt files... finished 
 [============================]


all files could be decrypted successfully!
Server side encryption remains enabled
➜  owncloud3 git:(master) ✗ ./occ encryption:encrypt-all 
Cannot load Xdebug - it was already loaded


You are about to encrypt all files stored in your ownCloud installation.
Depending on the number of available files, and their size, this may take quite some time.
Please ensure that no user accesses their files during this time!
Note: The encryption module you use determines which files get encrypted.

Do you really want to continue? (y/n) y


Encrypt all files with the Default encryption module
====================================================


Use master key to encrypt all files.


Start to encrypt users files
----------------------------



 all files encrypted 
 [============================]

➜  owncloud3 git:(master) ✗ 
```
- Was able to open the welcome.txt and read the contents.

#### Master key re-encryption
- Create 2 users `user1` and `admin` and encrypt with masterkey
- Login to both users
- Execute recreate masterkey command. Below are the logs to verify the result:
```
➜  owncloud3 git:(master) ✗ rm -fr config/config.php data; ./occ maintenance:install --admin-user "admin" --admin-pass "admin"; ./occ a:e user_management; ./occ a:e encryption; ./occ encryption:enable; ./occ encryption:select-encryption-type masterkey -y; ./occ user:add user1
Cannot load Xdebug - it was already loaded
creating sqlite db
ownCloud was successfully installed
Cannot load Xdebug - it was already loaded
user_management enabled
Cannot load Xdebug - it was already loaded
encryption enabled
Cannot load Xdebug - it was already loaded
Encryption enabled

Default module: OC_DEFAULT_MODULE
Cannot load Xdebug - it was already loaded
Master key successfully enabled.
Cannot load Xdebug - it was already loaded
Enter password: 
Confirm password: 
The user "user1" was created successfully
➜  owncloud3 git:(master) ✗ ./occ encryption:recreate-master-key -y
Cannot load Xdebug - it was already loaded
Decryption started

    1 [->--------------------------]prepare encryption modules...
 done.


 decrypt files for user user1 (2 of 2): /user1/files/welcome.txt 
 [--->------------------------]

 starting to decrypt files... finished 
 [============================]


all files could be decrypted successfully!
    1 [============================]
Decryption completed

Encryption started

Waiting for creating new masterkey

New masterkey created successfully



Encrypt all files with the Default encryption module
====================================================


Use master key to encrypt all files.


Start to encrypt users files
----------------------------



 all files encrypted 
 [============================]


Encryption completed successfully

➜  owncloud3 git:(master) ✗
```
- After relogin back to `admin` and `user1`, was able to read the files of the users.

#### User keys encryption
- Create 2 users `user1` and `admin` and encrypt with user-keys
- Login to both users
- Decrypt `user1` with decrypt-all command
- Execute encrypt-all command. Below are the screen shots to verify the result:
```
➜  owncloud3 git:(master) ✗ rm -fr config/config.php data; ./occ maintenance:install --admin-user "admin" --admin-pass "admin"; ./occ a:e user_management; ./occ a:e encryption; ./occ encryption:enable; ./occ encryption:select-encryption-type user-keys -y; ./occ user:add user1
Cannot load Xdebug - it was already loaded
creating sqlite db
ownCloud was successfully installed
Cannot load Xdebug - it was already loaded
user_management enabled
Cannot load Xdebug - it was already loaded
encryption enabled
Cannot load Xdebug - it was already loaded
Encryption enabled

Default module: OC_DEFAULT_MODULE
Cannot load Xdebug - it was already loaded
User key successfully enabled.
Cannot load Xdebug - it was already loaded
Enter password: 
Confirm password: 
The user "user1" was created successfully
➜  owncloud3 git:(master) ✗ ./occ encryption:decrypt-all user1
Cannot load Xdebug - it was already loaded
Disable server side encryption... done.


You are about to start to decrypt all files stored in user1's account.
It will depend on the encryption module and your setup if this is possible.
Depending on the number and size of your files this can take some time
Please make sure that no user access his files during this process!

Do you really want to continue? (y/n) y
prepare encryption modules...
 done.


 starting to decrypt files... 
 [->--------------------------]
Prepare "Default encryption module"

Configuring encryption module for decryption with user based keys
 decrypt files for user user1 (1 of 1): /user1/files/welcome.txt 
 [-->-------------------------]

 starting to decrypt files... finished 
 [============================]


all files could be decrypted successfully!
Server side encryption remains enabled
➜  owncloud3 git:(master) ✗ ./occ encryption:encrypt-all
Cannot load Xdebug - it was already loaded


You are about to encrypt all files stored in your ownCloud installation.
Depending on the number of available files, and their size, this may take quite some time.
Please ensure that no user accesses their files during this time!
Note: The encryption module you use determines which files get encrypted.

Do you really want to continue? (y/n) y


Encrypt all files with the Default encryption module
====================================================


Create key-pair for every user
------------------------------

This module will encrypt all files in the users files folder initially.
Already existing versions and files in the trash bin will not be encrypted.



 Key-pair created for all users 
 [>---------------------------]

Start to encrypt users files
----------------------------



 all files encrypted 
 [============================]

Generated encryption key passwords
----------------------------------


All users already had a key-pair, no further action needed.



➜  owncloud3 git:(master) ✗
```
- Was able to read files of `admin` and `user1`.

**Comment by PVince81** [comment]
assuming this code also applies to user key encryption ? can you do a quick check that it also works ?

**Comment by sharidas** [comment]
> assuming this code also applies to user key encryption ? can you do a quick check that it also works ?

Yes it does work. Below are the steps done to verify:

- Create 2 users `admin` and `user1` with user-keys encrypted
- Login to both users
- Decrypt `user1` with decrypt-all command
- Execute `encrypt-all` on the file system. Below are the console logs to be verified:
```
➜  owncloud git:(master) ✗ rm -fr config/config.php data; ./occ maintenance:install --admin-user "admin" --admin-pass "admin"; ./occ a:e user_management; ./occ a:e encryption; ./occ encryption:enable; ./occ encryption:select-encryption-type user-keys -y; ./occ user:add user1
Cannot load Xdebug - it was already loaded
creating sqlite db
ownCloud was successfully installed
Cannot load Xdebug - it was already loaded
user_management enabled
Cannot load Xdebug - it was already loaded
encryption enabled
Cannot load Xdebug - it was already loaded
Encryption enabled

Default module: OC_DEFAULT_MODULE
Cannot load Xdebug - it was already loaded
User key successfully enabled.
Cannot load Xdebug - it was already loaded
Enter password: 
Confirm password: 
The user "user1" was created successfully
➜  owncloud git:(master) ✗ ./occ encryption:decrypt-all user1               
Cannot load Xdebug - it was already loaded
Disable server side encryption... done.


You are about to start to decrypt all files stored in user1's account.
It will depend on the encryption module and your setup if this is possible.
Depending on the number and size of your files this can take some time
Please make sure that no user access his files during this process!

Do you really want to continue? (y/n) y
prepare encryption modules...
 done.


 starting to decrypt files... 
 [->--------------------------]
Prepare "Default encryption module"

Configuring encryption module for decryption with user based keys
 decrypt files for user user1 (1 of 1): /user1/files/welcome.txt 
 [-->-------------------------]

 starting to decrypt files... finished 
 [============================]


all files could be decrypted successfully!
Server side encryption remains enabled
➜  owncloud git:(master) ✗ ./occ encryption:encrypt-all
Cannot load Xdebug - it was already loaded


You are about to encrypt all files stored in your ownCloud installation.
Depending on the number of available files, and their size, this may take quite some time.
Please ensure that no user accesses their files during this time!
Note: The encryption module you use determines which files get encrypted.

Do you really want to continue? (y/n) y


Encrypt all files with the Default encryption module
====================================================


Create key-pair for every user
------------------------------

This module will encrypt all files in the users files folder initially.
Already existing versions and files in the trash bin will not be encrypted.



 Key-pair created for all users 
 [>---------------------------]

Start to encrypt users files
----------------------------



 all files encrypted 
 [============================]

Generated encryption key passwords
----------------------------------


All users already had a key-pair, no further action needed.



➜  owncloud git:(master) ✗
```

**Comment by PVince81** [comment]
please merge and backport if CI passes

**Comment by sharidas** [comment]
Backport to stable10 -> https://github.com/owncloud/core/pull/33206

**Pull request merged**
