### PR TITLE
Adjust acceptance test step text changed in core

### PR DESCRIPTION
**Pull request by phil-davis**
Issue #72

### CODE REVIEW

**Comment by phil-davis** [comment]
I guess this also needs:
- core master PR https://github.com/owncloud/core/pull/33587
- core stable10 PR https://github.com/owncloud/core/pull/33588

to be in the QA tarballs, so that other known-to-fail tests will be skipped.

**Comment by phil-davis** [comment]
I restarted the drone job (again) just now. Maybe in another day or 2 it will actually run :(

**Comment by phil-davis** [comment]
drone did not want to restart CI for this job, so I rebased and force-pushed just now.

**Comment by individual-it** [comment]
@ownclouders rebase

**Comment by individual-it** [comment]
CI failed because of MySQL timeout, restarted the build

**Pull request merged**
