### PR TITLE
Release 1.5.3

### PR DESCRIPTION
**Pull request by GeraldLeikam**
merge back to master after release

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiCoreMKey-40-6-master-mysql8.0-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/encryption/2609/33

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiCoreMKey-40-8-master-mysql8.0-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/encryption/2609/35

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIcoreMKey-20-19-master-chrome-mysql8.0-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/encryption/2609/93

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIcoreMKey-20-14-master-chrome-mysql8.0-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/encryption/2609/88

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiCoreMKey-40-2-master-mysql8.0-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/encryption/2609/29

**Comment by phil-davis** [comment]
Dumb drone-docker problems in pipelines - I restarted CI.

**Review by jnweiger — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
