### PR TITLE
[tests-only] Use owncloudci/wait-for docker image

### PR DESCRIPTION
**Pull request by phil-davis**
Update the drone starlark code the same as https://github.com/owncloud/activity/pull/1036

### CODE REVIEW

**Review by kiranparajuli589 — APPROVED** [review]

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>cliCoreMKey-7-5-master-mysql8.0-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/encryption/2214/72/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>cliCoreMKey-7-2-master-mysql8.0-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/encryption/2214/69/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>cliCoreMKey-7-2-master-mysql8.0-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/encryption/2217/69/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>cliCoreMKey-7-6-master-mysql8.0-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/encryption/2218/73/1

**Pull request merged**
