### PR TITLE
 [phpunit] Fail on warnings

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by mmattel** [comment]
This PR is open and unchanged for a long time.
stable10 got merged a while ago.
Any reason why this is still open?

**Comment by DeepDiver1975** [comment]
@ownclouders rebase

**Comment by PVince81** [comment]
@ownclouders rebase

**Comment by PVince81** [comment]
seems the test run is still queued: https://drone.owncloud.com/owncloud/encryption/285

**Comment by DeepDiver1975** [comment]
@ownclouders rebase

**Pull request merged**
