### PR TITLE
Delete bug demonstration for quota feature from `encryption` app

### PR DESCRIPTION
**Pull request by SagarGi**
### Description
This PR deletes the `apiEncryption/quotaOc10Issue40140.feature`  from this app since the quota handling has been improved and fixed with this PR https://github.com/owncloud/core/pull/39895. So The bug demonstration can be deleted as this test scenarios is run on this app with `apiMain/quota.feature` from core.

### Related issue
https://github.com/owncloud/encryption/issues/353

### CODE REVIEW

**Comment by phil-davis** [comment]
Note: these tests were added to the encryption test suite in PR #346 because the quota bug behaved a little bit differently in encryption compared to core. Now that the c ore bug has been fixed, the tests in core should pass the same when run with encryption enabled, and we delete the bug-demonstration scenarios that were added in encryption.

**Review by phil-davis — APPROVED** [review]

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiCoreMKey-40-6-master-mysql8.0-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/encryption/2565/33

**Comment by SagarGi** [comment]
@phil-davis https://drone.owncloud.com/owncloud/encryption/2565/33/20 this looks like a hard failure. @grgprarup is looking to it.

**Comment by phil-davis** [comment]
I also pushed some cleanup and bump of dependencies:

Makefile target "clean" was not removing the vendor directory. Add that to Makefile.

Bump bamarni/composer-bin-plugin (1.7.0 => 1.8.0)

**Comment by phil-davis** [comment]
Some drone pipelines seemed to be hung. I cancelled the job, destroyed the old drone agents, and restarted CI.

**Comment by SagarGi** [comment]
https://drone.owncloud.com/owncloud/encryption/2565/33/20 this fail must pass if this PR gets merged. https://github.com/owncloud/core/pull/40224#pullrequestreview-1046062465

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/encryption/2571/33/20
```
runsh: Total unexpected failed scenarios throughout the test run:
apiMain/quota.feature:358
```
That has been skipped now - https://github.com/owncloud/core/pull/40224

I will restart CI.

**Comment by phil-davis** [comment]
drone is being very annoying. I restarted again (20 minutes ago), because one of the pipelines seemed to be hung,

**Pull request merged**
