### PR TITLE
Fix minor wording corrections in command

### PR DESCRIPTION
**Pull request by sharidas**
Fix minor wording corrections in the command.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

Also added here to help with #118 code alignment: (by phil-davis)
- Bump all ownCloud copyright consistently to 2019
- Fix GmbH typo in copyright
- Adjust encryption code format to match what is in core stable10

That gets the code here closer to core stable10. See core `stable10` PR https://github.com/owncloud/core/pull/35015 for changes in the opposite direction, that get core `stable10` closer to the `encryption` app repo.

### CODE REVIEW

**Comment by sharidas** [comment]
The backport of this commit is https://github.com/owncloud/core/pull/35000. To be precise the commit https://github.com/owncloud/core/pull/35000/commits/c530242aa0114382d007921daa2c390ab393d97d

**Comment by sharidas** [comment]
@phil-davis Updated the PR by removing 
```
use OC\Files\Cache\Cache;
```

**Comment by phil-davis** [comment]
> @phil-davis Updated the PR by removing
> 
> ```
> use OC\Files\Cache\Cache;
> ```

If that is an unused `use` statement, then great, delete it. Now that same delete  needs to be done in cire `stable10` also, to keep the code as much the same as possible.

**Comment by phil-davis** [comment]
Rebased, let's see what CI says now.

**Comment by phil-davis** [comment]
@PVince81 this  needs a repo-god to override the codecov. Nothing here changes existing code logic or unit test logic.

**Pull request merged**
